# Cross file for building m1n1 on macOS (Homebrew LLVM) or with clang generally.
# Usage:
#   brew install llvm lld
#   meson setup build --cross-file cross/aarch64-clang.ini
#   ninja -C build

[binaries]
c = ['clang', '--target=aarch64-elf']
rust = ['@GLOBAL_SOURCE_ROOT@/tools/rustc-bootstrap.sh', '--target=aarch64-unknown-none-softfloat']
ar = 'llvm-ar'
strip = 'llvm-strip'
objcopy = 'llvm-objcopy'
c_ld = 'lld'
exe_wrapper = []

[built-in options]
c_args = ['-ffreestanding', '-nostdinc']
c_link_args = ['-fuse-ld=lld', '-nostdlib']

[properties]
needs_exe_wrapper = true
skip_sanity_check = true

[host_machine]
system = 'none'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
